version: '3'
services:
    message-server:
        container_name: prestadores-service
        build:
            context: prestadores-service
            dockerfile: Dockerfile
        image: prestadores-service:1.0.0
        ports:
            - 8081:8080
        networks:
            - poc-gisa-net

networks:
    poc-gisa-net:
        driver: bridge
